Name: project
Host: 0.0.0.0
Port: 801

DB:
  DataSource: root:pujian123@tcp(172.16.10.183:4306)/im-center?charset=utf8mb4&loc=Asia%2FShanghai&parseTime=true   //root:pujian123@tcp(172.16.10.183:4306)/im-center
#redis配置
Cache:
  - Host: 172.16.10.183:6379    //172.16.10.183:6379
  # Pass: xxx