// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"github.com/zeromicro/go-zero/rest"

	"project-admin/test2/internal/svc"
	"project-admin/test2/internal/handler/swaggerDoc"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/docData",
				Handler: swaggerDoc.DocDataHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/doc",
				Handler: swaggerDoc.DocHandler(serverCtx),
			},
		},
	)
}
