Name: project
Host: 0.0.0.0
Port: 802

DB:
  DataSource: root:lsm.1018@tcp(127.0.0.1:3306)/im-center?charset=utf8mb4&loc=Asia%2FShanghai&parseTime=true
  #  DataSource: root:pujian123@tcp(172.16.10.183:4306)/im-center?charset=utf8mb4&loc=Asia%2FShanghai&parseTime=true
#redis配置
Cache:
  - Host: 127.0.0.1:6379
  #  - Host: 172.16.10.183:6379
  # Pass: xxx