// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	Application "project-admin/projectBuilds/project23/internal/handler/Application"
	ApplicationConfig "project-admin/projectBuilds/project23/internal/handler/ApplicationConfig"
	Config "project-admin/projectBuilds/project23/internal/handler/Config"
	Doc "project-admin/projectBuilds/project23/internal/handler/Doc"
	DocHistory "project-admin/projectBuilds/project23/internal/handler/DocHistory"
	Group "project-admin/projectBuilds/project23/internal/handler/Group"
	GroupGroupRelation "project-admin/projectBuilds/project23/internal/handler/GroupGroupRelation"
	Project "project-admin/projectBuilds/project23/internal/handler/Project"
	UserGroup "project-admin/projectBuilds/project23/internal/handler/UserGroup"
	"project-admin/projectBuilds/project23/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: Group.CreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/",
				Handler: Group.UpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/",
				Handler: Group.DeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: Group.GetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/gets",
				Handler: Group.GetsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/admin/Group/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: UserGroup.CreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/",
				Handler: UserGroup.UpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/",
				Handler: UserGroup.DeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: UserGroup.GetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/gets",
				Handler: UserGroup.GetsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/admin/UserGroup/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: GroupGroupRelation.CreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/",
				Handler: GroupGroupRelation.UpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/",
				Handler: GroupGroupRelation.DeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: GroupGroupRelation.GetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/gets",
				Handler: GroupGroupRelation.GetsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/admin/GroupGroupRelation/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: Config.CreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/",
				Handler: Config.UpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/",
				Handler: Config.DeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: Config.GetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/gets",
				Handler: Config.GetsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/admin/Config/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: Project.CreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/",
				Handler: Project.UpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/",
				Handler: Project.DeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: Project.GetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/gets",
				Handler: Project.GetsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/admin/Project/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: Application.CreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/",
				Handler: Application.UpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/",
				Handler: Application.DeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: Application.GetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/gets",
				Handler: Application.GetsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/admin/Application/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: ApplicationConfig.CreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/",
				Handler: ApplicationConfig.UpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/",
				Handler: ApplicationConfig.DeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: ApplicationConfig.GetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/gets",
				Handler: ApplicationConfig.GetsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/admin/ApplicationConfig/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: Doc.CreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/",
				Handler: Doc.UpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/",
				Handler: Doc.DeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: Doc.GetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/gets",
				Handler: Doc.GetsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/admin/Doc/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: DocHistory.CreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/",
				Handler: DocHistory.UpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/",
				Handler: DocHistory.DeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: DocHistory.GetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/gets",
				Handler: DocHistory.GetsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/admin/DocHistory/v1"),
	)
}
