// Code generated by goctl. DO NOT EDIT!

package test1

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	friendFieldNames          = builder.RawFieldNames(&Friend{})
	friendRows                = strings.Join(friendFieldNames, ",")
	friendRowsExpectAutoSet   = strings.Join(stringx.Remove(friendFieldNames, "`create_at`", "`created_at`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`", "`state`"), ",")
	friendRowsWithPlaceHolder = strings.Join(stringx.Remove(friendFieldNames, "`id`", "`create_at`", "`created_at`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`"), "=?,") + "=?"
	friendListRows            = strings.Join(builder.RawFieldNames(&Friend{}), ",")

	cacheFriendIdPrefix                  = "cache:friend:id:"
	cacheFriendApplyUserAcceptUserPrefix = "cache:friend:applyUser:acceptUser:"
)

type (
	friendModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *Friend) (sql.Result, error)
		FindOne(ctx context.Context, session sqlx.Session, id int64, resp interface{}) (err error)
		FindOneByApplyUserAcceptUser(ctx context.Context, applyUser int64, acceptUser int64) (*Friend, error)
		Update(ctx context.Context, session sqlx.Session, data *Friend) error
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultFriendModel struct {
		sqlc.CachedConn
		table string
	}

	Friend struct {
		Id          int64     `db:"id"`           // 自增主键
		ApplyUser   int64     `db:"apply_user"`   // 申请用户id
		ApplyDevice string    `db:"apply_device"` // 申请设备id
		AcceptUser  int64     `db:"accept_user"`  // 接受用户id
		ApplyReason string    `db:"apply_reason"` // 申请理由
		Extra       string    `db:"extra"`        // 附加属性
		State       int64     `db:"state"`        // 状态，-2：拉黑，-1：拒绝，0：申请中，1：同意
		CreateTime  time.Time `db:"create_time"`  // 创建时间
		UpdateTime  time.Time `db:"update_time"`  // 更新时间
	}
)

func newFriendModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultFriendModel {
	return &defaultFriendModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`friend`",
	}
}

func (m *defaultFriendModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	data := &Friend{}
	err := m.FindOne(ctx, session, id, data)
	if err != nil {
		return err
	}
	friendApplyUserAcceptUserKey := fmt.Sprintf("%s%v:%v", cacheFriendApplyUserAcceptUserPrefix, data.ApplyUser, data.AcceptUser)
	friendIdKey := fmt.Sprintf("%s%v", cacheFriendIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, friendApplyUserAcceptUserKey, friendIdKey)
	return err
}

func (m *defaultFriendModel) FindOne(ctx context.Context, session sqlx.Session, id int64, resp interface{}) (err error) {
	friendIdKey := fmt.Sprintf("%s%v", cacheFriendIdPrefix, id)
	err = m.QueryRowCtx(ctx, resp, friendIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", friendRows, m.table)
		if session != nil {
			return session.QueryRowCtx(ctx, v, query, id)
		}
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return nil
	case sqlc.ErrNotFound:
		return ErrNotFound
	default:
		return err
	}
}

func (m *defaultFriendModel) FindOneByApplyUserAcceptUser(ctx context.Context, applyUser int64, acceptUser int64) (*Friend, error) {
	friendApplyUserAcceptUserKey := fmt.Sprintf("%s%v:%v", cacheFriendApplyUserAcceptUserPrefix, applyUser, acceptUser)
	var resp Friend
	err := m.QueryRowIndexCtx(ctx, &resp, friendApplyUserAcceptUserKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `apply_user` = ? and `accept_user` = ? limit 1", friendRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, applyUser, acceptUser); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFriendModel) Insert(ctx context.Context, session sqlx.Session, data *Friend) (sql.Result, error) {
	friendApplyUserAcceptUserKey := fmt.Sprintf("%s%v:%v", cacheFriendApplyUserAcceptUserPrefix, data.ApplyUser, data.AcceptUser)
	friendIdKey := fmt.Sprintf("%s%v", cacheFriendIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, friendRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.Id, data.ApplyUser, data.ApplyDevice, data.AcceptUser, data.ApplyReason, data.Extra, data.State)
		}
		return conn.ExecCtx(ctx, query, data.Id, data.ApplyUser, data.ApplyDevice, data.AcceptUser, data.ApplyReason, data.Extra, data.State)
	}, friendApplyUserAcceptUserKey, friendIdKey)
	return ret, err
}

func (m *defaultFriendModel) Update(ctx context.Context, session sqlx.Session, newData *Friend) error {
	data := &Friend{}
	err := m.FindOne(ctx, session, newData.Id, data)
	if err != nil {
		return err
	}

	friendApplyUserAcceptUserKey := fmt.Sprintf("%s%v:%v", cacheFriendApplyUserAcceptUserPrefix, data.ApplyUser, data.AcceptUser)
	friendIdKey := fmt.Sprintf("%s%v", cacheFriendIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, friendRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, newData.ApplyUser, newData.ApplyDevice, newData.AcceptUser, newData.ApplyReason, newData.Extra, newData.State, newData.Id)
		}
		return conn.ExecCtx(ctx, query, newData.ApplyUser, newData.ApplyDevice, newData.AcceptUser, newData.ApplyReason, newData.Extra, newData.State, newData.Id)
	}, friendApplyUserAcceptUserKey, friendIdKey)
	return err
}

func (m *defaultFriendModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheFriendIdPrefix, primary)
}

func (m *defaultFriendModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", friendRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultFriendModel) tableName() string {
	return m.table
}
