// Code generated by goctl. DO NOT EDIT!

package test1

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	groupMsgFieldNames          = builder.RawFieldNames(&GroupMsg{})
	groupMsgRows                = strings.Join(groupMsgFieldNames, ",")
	groupMsgRowsExpectAutoSet   = strings.Join(stringx.Remove(groupMsgFieldNames, "`update_at`", "`updated_at`", "`update_time`", "`create_at`", "`created_at`", "`create_time`", "`state`"), ",")
	groupMsgRowsWithPlaceHolder = strings.Join(stringx.Remove(groupMsgFieldNames, "`id`", "`update_at`", "`updated_at`", "`update_time`", "`create_at`", "`created_at`", "`create_time`"), "=?,") + "=?"
	groupMsgListRows            = strings.Join(builder.RawFieldNames(&GroupMsg{}), ",")

	cacheGroupMsgIdPrefix                 = "cache:groupMsg:id:"
	cacheGroupMsgSenderIdReceiverIdPrefix = "cache:groupMsg:senderId:receiverId:"
)

type (
	groupMsgModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *GroupMsg) (sql.Result, error)
		FindOne(ctx context.Context, session sqlx.Session, id int64, resp interface{}) (err error)
		FindOneBySenderIdReceiverId(ctx context.Context, senderId int64, receiverId int64) (*GroupMsg, error)
		Update(ctx context.Context, session sqlx.Session, data *GroupMsg) error
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultGroupMsgModel struct {
		sqlc.CachedConn
		table string
	}

	GroupMsg struct {
		Id               int64     `db:"id"`                 // 自增主键
		Seq              int64     `db:"seq"`                // 消息序列号,每个单聊都维护一个消息序列号
		SenderType       int64     `db:"sender_type"`        // 发送者类型：1群内，2转发
		SenderId         int64     `db:"sender_id"`          // 发送者id
		SenderDeviceId   string    `db:"sender_device_id"`   // 发送设备id
		ReceiverId       int64     `db:"receiver_id"`        // 接收者id(group_id)
		ReceiverDeviceId string    `db:"receiver_device_id"` // 接收设备id：多个设备id"，"隔开，*表示全部设备
		AtUserIds        string    `db:"at_user_ids"`        // 需要@的用户id列表，多个用户用@隔开
		MsgType          int64     `db:"msg_type"`           // 消息类型：0文本、1图文、2语音、3视频、地址、4链接
		Content          string    `db:"content"`            // 消息内容
		ParentId         int64     `db:"parent_id"`          // 父级id，引用功能
		SendTime         string    `db:"send_time"`          // 消息发送时间
		State            int64     `db:"state"`              // 消息状态，-3接收者删除，-2发送者删除，-1撤回，0未处理，1已读
		CreateTime       time.Time `db:"create_time"`        // 创建时间
		UpdateTime       time.Time `db:"update_time"`        // 更新时间
	}
)

func newGroupMsgModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultGroupMsgModel {
	return &defaultGroupMsgModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`group_msg`",
	}
}

func (m *defaultGroupMsgModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	data := &GroupMsg{}
	err := m.FindOne(ctx, session, id, data)
	if err != nil {
		return err
	}
	groupMsgIdKey := fmt.Sprintf("%s%v", cacheGroupMsgIdPrefix, id)
	groupMsgSenderIdReceiverIdKey := fmt.Sprintf("%s%v:%v", cacheGroupMsgSenderIdReceiverIdPrefix, data.SenderId, data.ReceiverId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, groupMsgIdKey, groupMsgSenderIdReceiverIdKey)
	return err
}

func (m *defaultGroupMsgModel) FindOne(ctx context.Context, session sqlx.Session, id int64, resp interface{}) (err error) {
	groupMsgIdKey := fmt.Sprintf("%s%v", cacheGroupMsgIdPrefix, id)
	err = m.QueryRowCtx(ctx, resp, groupMsgIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", groupMsgRows, m.table)
		if session != nil {
			return session.QueryRowCtx(ctx, v, query, id)
		}
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return nil
	case sqlc.ErrNotFound:
		return ErrNotFound
	default:
		return err
	}
}

func (m *defaultGroupMsgModel) FindOneBySenderIdReceiverId(ctx context.Context, senderId int64, receiverId int64) (*GroupMsg, error) {
	groupMsgSenderIdReceiverIdKey := fmt.Sprintf("%s%v:%v", cacheGroupMsgSenderIdReceiverIdPrefix, senderId, receiverId)
	var resp GroupMsg
	err := m.QueryRowIndexCtx(ctx, &resp, groupMsgSenderIdReceiverIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `sender_id` = ? and `receiver_id` = ? limit 1", groupMsgRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, senderId, receiverId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGroupMsgModel) Insert(ctx context.Context, session sqlx.Session, data *GroupMsg) (sql.Result, error) {
	groupMsgIdKey := fmt.Sprintf("%s%v", cacheGroupMsgIdPrefix, data.Id)
	groupMsgSenderIdReceiverIdKey := fmt.Sprintf("%s%v:%v", cacheGroupMsgSenderIdReceiverIdPrefix, data.SenderId, data.ReceiverId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, groupMsgRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.Id, data.Seq, data.SenderType, data.SenderId, data.SenderDeviceId, data.ReceiverId, data.ReceiverDeviceId, data.AtUserIds, data.MsgType, data.Content, data.ParentId, data.SendTime, data.State)
		}
		return conn.ExecCtx(ctx, query, data.Id, data.Seq, data.SenderType, data.SenderId, data.SenderDeviceId, data.ReceiverId, data.ReceiverDeviceId, data.AtUserIds, data.MsgType, data.Content, data.ParentId, data.SendTime, data.State)
	}, groupMsgIdKey, groupMsgSenderIdReceiverIdKey)
	return ret, err
}

func (m *defaultGroupMsgModel) Update(ctx context.Context, session sqlx.Session, newData *GroupMsg) error {
	data := &GroupMsg{}
	err := m.FindOne(ctx, session, newData.Id, data)
	if err != nil {
		return err
	}

	groupMsgIdKey := fmt.Sprintf("%s%v", cacheGroupMsgIdPrefix, data.Id)
	groupMsgSenderIdReceiverIdKey := fmt.Sprintf("%s%v:%v", cacheGroupMsgSenderIdReceiverIdPrefix, data.SenderId, data.ReceiverId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, groupMsgRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, newData.Seq, newData.SenderType, newData.SenderId, newData.SenderDeviceId, newData.ReceiverId, newData.ReceiverDeviceId, newData.AtUserIds, newData.MsgType, newData.Content, newData.ParentId, newData.SendTime, newData.State, newData.Id)
		}
		return conn.ExecCtx(ctx, query, newData.Seq, newData.SenderType, newData.SenderId, newData.SenderDeviceId, newData.ReceiverId, newData.ReceiverDeviceId, newData.AtUserIds, newData.MsgType, newData.Content, newData.ParentId, newData.SendTime, newData.State, newData.Id)
	}, groupMsgIdKey, groupMsgSenderIdReceiverIdKey)
	return err
}

func (m *defaultGroupMsgModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheGroupMsgIdPrefix, primary)
}

func (m *defaultGroupMsgModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", groupMsgRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultGroupMsgModel) tableName() string {
	return m.table
}
