// Code generated by goctl. DO NOT EDIT!

package test1

import (
	"context"
	"database/sql"
	"fmt"
	"project-admin/common/sqlUtils"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	singleMsgFieldNames          = builder.RawFieldNames(&SingleMsg{})
	singleMsgRows                = strings.Join(singleMsgFieldNames, ",")
	singleMsgRowsExpectAutoSet   = strings.Join(stringx.Remove(singleMsgFieldNames, "`update_at`", "`updated_at`", "`update_time`", "`create_at`", "`created_at`", "`create_time`", "`state`"), ",")
	singleMsgRowsWithPlaceHolder = strings.Join(stringx.Remove(singleMsgFieldNames, "`id`", "`update_at`", "`updated_at`", "`update_time`", "`create_at`", "`created_at`", "`create_time`"), "=?,") + "=?"
	singleMsgListRows            = strings.Join(builder.RawFieldNames(&SingleMsg{}), ",")

	cacheSingleMsgIdPrefix                 = "cache:singleMsg:id:"
	cacheSingleMsgSenderIdReceiverIdPrefix = "cache:singleMsg:senderId:receiverId:"
)

type (
	singleMsgModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *SingleMsg) (sql.Result, error)
		FindOne(ctx context.Context, session sqlx.Session, id int64, resp interface{}) (err error)
		FindOneBySenderIdReceiverId(ctx context.Context, senderId int64, receiverId int64) (*SingleMsg, error)
		Update(ctx context.Context, session sqlx.Session, data *SingleMsg) error
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultSingleMsgModel struct {
		sqlc.CachedConn
		table string
	}

	SingleMsg struct {
		Id               int64     `db:"id"`                 // 自增主键
		Seq              int64     `db:"seq"`                // 消息序列号,每个单聊都维护一个消息序列号
		SenderType       int64     `db:"sender_type"`        // 发送者类型：1朋友，2打招呼，3转发
		SenderId         int64     `db:"sender_id"`          // 发送者id
		SenderDeviceId   string    `db:"sender_device_id"`   // 发送设备id
		ReceiverId       int64     `db:"receiver_id"`        // 接收者id(friendId)
		ReceiverDeviceId string    `db:"receiver_device_id"` // 接收设备id：多个设备id"，"隔开，*表示全部设备
		MsgType          int64     `db:"msg_type"`           // 消息类型：0文本、1图文、2语音、3视频、4链接
		Content          string    `db:"content"`            // 消息内容
		ParentId         int64     `db:"parent_id"`          // 父级id，引用功能
		SendTime         string    `db:"send_time"`          // 消息发送时间
		State            int64     `db:"state"`              // 消息状态：-1撤回，0未处理，1已读
		CreateTime       time.Time `db:"create_time"`        // 创建时间
		UpdateTime       time.Time `db:"update_time"`        // 更新时间
	}
)

func newSingleMsgModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultSingleMsgModel {
	return &defaultSingleMsgModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`single_msg`",
	}
}

func (m *defaultSingleMsgModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	data := &SingleMsg{}
	err := m.FindOne(ctx, session, id, data)
	if err != nil {
		return err
	}
	singleMsgIdKey := fmt.Sprintf("%s%v", cacheSingleMsgIdPrefix, id)
	singleMsgSenderIdReceiverIdKey := fmt.Sprintf("%s%v:%v", cacheSingleMsgSenderIdReceiverIdPrefix, data.SenderId, data.ReceiverId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, singleMsgIdKey, singleMsgSenderIdReceiverIdKey)
	return err
}

func (m *defaultSingleMsgModel) FindOne(ctx context.Context, session sqlx.Session, id int64, resp interface{}) (err error) {
	singleMsgIdKey := fmt.Sprintf("%s%v", cacheSingleMsgIdPrefix, id)
	err = m.QueryRowCtx(ctx, resp, singleMsgIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", singleMsgRows, m.table)
		if session != nil {
			return session.QueryRowCtx(ctx, v, query, id)
		}
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return nil
	case sqlc.ErrNotFound:
		return ErrNotFound
	default:
		return err
	}
}

func (m *defaultSingleMsgModel) FindOneBySenderIdReceiverId(ctx context.Context, senderId int64, receiverId int64) (*SingleMsg, error) {
	singleMsgSenderIdReceiverIdKey := fmt.Sprintf("%s%v:%v", cacheSingleMsgSenderIdReceiverIdPrefix, senderId, receiverId)
	var resp SingleMsg
	err := m.QueryRowIndexCtx(ctx, &resp, singleMsgSenderIdReceiverIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `sender_id` = ? and `receiver_id` = ? limit 1", singleMsgRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, senderId, receiverId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSingleMsgModel) Insert(ctx context.Context, session sqlx.Session, data *SingleMsg) (sql.Result, error) {
	singleMsgIdKey := fmt.Sprintf("%s%v", cacheSingleMsgIdPrefix, data.Id)
	singleMsgSenderIdReceiverIdKey := fmt.Sprintf("%s%v:%v", cacheSingleMsgSenderIdReceiverIdPrefix, data.SenderId, data.ReceiverId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, singleMsgRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.Id, data.Seq, data.SenderType, data.SenderId, data.SenderDeviceId, data.ReceiverId, data.ReceiverDeviceId, data.MsgType, data.Content, data.ParentId, data.SendTime)
		}
		return conn.ExecCtx(ctx, query, data.Id, data.Seq, data.SenderType, data.SenderId, data.SenderDeviceId, data.ReceiverId, data.ReceiverDeviceId, data.MsgType, data.Content, data.ParentId, data.SendTime)
	}, singleMsgIdKey, singleMsgSenderIdReceiverIdKey)
	return ret, err
}

func (m *defaultSingleMsgModel) Update(ctx context.Context, session sqlx.Session, newData *SingleMsg) error {
	data := &SingleMsg{}
	err := m.FindOne(ctx, session, newData.Id, data)
	if err != nil {
		return err
	}

	singleMsgIdKey := fmt.Sprintf("%s%v", cacheSingleMsgIdPrefix, data.Id)
	singleMsgSenderIdReceiverIdKey := fmt.Sprintf("%s%v:%v", cacheSingleMsgSenderIdReceiverIdPrefix, data.SenderId, data.ReceiverId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, strings.Join(sqlUtils.BuildFields(newData, sqlUtils.IsEmptyValue),", "))
		if session != nil {
			return session.Exec(query, newData.Id)
		}
		return conn.Exec(query, newData.Id)

		//query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, singleMsgRowsWithPlaceHolder)
		//if session != nil {
		//	return session.ExecCtx(ctx, query, newData.Seq, newData.SenderType, newData.SenderId, newData.SenderDeviceId, newData.ReceiverId, newData.ReceiverDeviceId, newData.MsgType, newData.Content, newData.ParentId, newData.SendTime, newData.State, newData.Id)
		//}
		//return conn.ExecCtx(ctx, query, newData.Seq, newData.SenderType, newData.SenderId, newData.SenderDeviceId, newData.ReceiverId, newData.ReceiverDeviceId, newData.MsgType, newData.Content, newData.ParentId, newData.SendTime, newData.State, newData.Id)
	}, singleMsgIdKey, singleMsgSenderIdReceiverIdKey)
	return err
}

func (m *defaultSingleMsgModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheSingleMsgIdPrefix, primary)
}

func (m *defaultSingleMsgModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", singleMsgRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSingleMsgModel) tableName() string {
	return m.table
}
